name: n2i_xni_cuda12
dependencies:
  - python=3.11
  - numpy=1.26
  - nvidia::cuda-toolkit=12.1.0
  - pytorch::pytorch=2.1.1
  - pytorch::torchvision
  - conda-forge::torchio=0.19
  - scipy=1.11.4
  - conda-forge::matplotlib=3.8.2
  - pillow=10.0.1
  - conda-forge::tifffile=2023.12.9
  - tqdm=4.65.0

  
